import { ClTooltip } from '@codelab/ui';
import Head from 'next/head';

import styles from '../scss/Home.module.css';

export default function Home() {
  
  const triggerChildren = <button>Tooltip Trigger</button>

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>

      <ClTooltip triggerProps={{children:triggerChildren}}>Test tooltip</ClTooltip>
      </main>
    </div>
  );
}
